In [ ]:
import math
import statistics
import numpy as np
import scipy
from scipy import linalg
print(" math functions")
print("floor(2.6):", math.floor(2.6))
print("ceil(1.1):", math.ceil(1.1))
print("sqrt(25):", math.sqrt(25))
print("isqrt(18):", math.isqrt(18))
print("gcd(12,16):", math.gcd(12, 16))



 math functions
floor(2.6): 2
ceil(1.1): 2
sqrt(25): 5.0
isqrt(18): 4
gcd(12,16): 4


In [ ]:
print("\nnumpy array attributes and methods")
arr = np.array([[1, 2],[3, 4]])
print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("sum:", np.sum(arr))
print("mean:", np.mean(arr))
print("sorted:", np.sort(arr, axis=None))
print("sin values:", np.sin(arr))




numpy array attributes and methods
ndim: 2
shape: (2, 2)
size: 4
sum: 10
mean: 2.5
sorted: [1 2 3 4]
sin values: [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


In [ ]:
print("\nDeterminant and Eigenvalues,eigenvectors")
matrix = np.array([[1, 2],[3, 4]])
print("Determinant", np.linalg.det(matrix))
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)



Determinant and Eigenvalues,eigenvectors
Determinant -2.0000000000000004
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:

print("\n1D list into 2D and 3D")
lst = [1, 2, 3, 4, 5, 6, 7, 8]
arr_1d = np.array(lst)
print("1D:", arr_1d)
print("2D:\n", arr_1d.reshape(2, 4))
print("3D:\n", arr_1d.reshape(2, 2, 2))




1D list into 2D and 3D
1D: [1 2 3 4 5 6 7 8]
2D:
 [[1 2 3 4]
 [5 6 7 8]]
3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print("\nGenerate matrices")
print("Zeros:\n", np.zeros((3,3)))
print("Ones:\n", np.ones((3, 3)))
print("Identity:\n", np.eye(3))
print("Random:\n", np.random.rand(3, 3))
print("Arange:\n", np.arange(5, 10, 2))




Generate matrices
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random:
 [[0.69565401 0.4294156  0.25002446]
 [0.60203063 0.33519344 0.55912634]
 [0.20954138 0.34246951 0.94415716]]
Arange:
 [5 7 9]


In [ ]:
print("\nDeterminant using scipy")
matrix2 = np.array([[2, 3], [4, 5]])
print("Determinant):", linalg.det(matrix2))



Determinant using scipy
Determinant): -2.000000000000001


In [ ]:

print("\nEigenvalues and Eigenvectors using scipy")
matrix3 = np.array([[2, 0], [0, 3]])
eigvals, eigvecs = linalg.eig(matrix3)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)


Eigenvalues and Eigenvectors using scipy
Eigenvalues: [2.+0.j 3.+0.j]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]
